- name: Backend setup
  hosts: backend
  become: yes

  vars:
    app_dir: /opt/Bite/backend

  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Install PM2
      npm:
        name: pm2
        global: yes

    - name: Clone Bite repo
      git:
        repo: https://github.com/GOWTHAMI9999/Bite.git
        dest: /opt/Bite
        force: yes

    - name: Install backend dependencies
      npm:
        path: "{{ app_dir }}"

    - name: Create backend .env file
      copy:
        dest: "{{ app_dir }}/.env"
        content: |
          PORT=3000
          MONGO_URI=mongodb://localhost:27017/bite

    - name: Start backend with PM2
      command: pm2 start server.js --name backend
      args:
        chdir: "{{ app_dir }}"

    - name: Create backend .env file
      copy:
        dest: "{{ app_dir }}/.env"
        content: |
          PORT=5000
          MONGO_URI=mongodb+srv://jaswanthlanka254_db_user:NEW_PASSWORD@cluster0.pjxdi57.mongodb.net/bite
          JWT_SECRET=some_long_random_secret
   
- name: Frontend setup
  hosts: frontend
  become: yes

  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Clone Bite repo
      git:
        repo: https://github.com/GOWTHAMI9999/Bite.git
        dest: /opt/Bite
        force: yes

    - name: Install frontend dependencies
      npm:
        path: /opt/Bite/frontend

    - name: Build frontend
      command: npm run build
      args:
        chdir: /opt/Bite/frontend

    - name: Copy dist to Nginx html
      copy:
        src: /opt/Bite/frontend/dist/
        dest: /var/www/html/
        remote_src: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

